spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: main-producto
          uri: http://main-producto:8086
          predicates:
            - Path=/producto/**
          filters:
            - StripPrefix=1
        - id: categorias
          uri: http://categorias:8081
          predicates:
            - Path=/categorias/**
          filters:
            - StripPrefix=1
        - id: enlaces
          uri: http://enlaces:8082
          predicates:
            - Path=/enlaces/**
          filters:
            - StripPrefix=1
        - id: ms-edicion
          uri: http://ms-edicion:8092
          predicates:
            - Path=/edicion/**
          filters:
            - StripPrefix=1
        - id: ms-figura
          uri: http://ms-figura:8091
          predicates:
            - Path=/figura/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true