server:
  port: '8092'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /doc/swagger-ui/index.html

ms:
  figura:
    url: http://ms-figura:8091

spring:
  application:
    name: ms-edicion
  jpa:
    show-sql: 'true'
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    url: jdbc:mysql://mysql-edicion:3306/db_edicion_dev?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update