server:
  port: '8080'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /doc/swagger-ui/index.html

spring:
  application:
<<<<<<< HEAD
    name: MainProducto
  profiles:
    active: dev
=======
    name: main-producto
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
  jpa:
    show-sql: 'true'

  profiles:
    active: dev 
>>>>>>> branchDaniel

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_producto_dev?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
<<<<<<< HEAD
    show-sql: 'true'
=======
>>>>>>> branchDaniel

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_producto_test?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_producto_prod?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
=======
>>>>>>> branchDaniel
      ddl-auto: update